fix(orb-ui): #162 matching agent displayed instead of group details
orb-community/orb pull request #2312
Opened 2023-04-20 18:10 UTC by joaoguilherme2003

2023-04-26 15:37 UTC, etaques requested changes

2023-04-26 15:37 UTC, etaques commented on ui/src/app/shared/components/orb/policy/policy-datasets/policy-datasets.component.html
> -    <button (click)="onOpenGroupDetails(row?.agent_group)"
I saw you created new function to perform the action.. Did you removed this **onOpenGroupDetails** function or still being used?

2023-04-26 23:26 UTC, etaques commented on ui/src/app/shared/components/orb/policy/policy-datasets/policy-datasets.component.html
> -    <button (click)="onOpenGroupDetails(row?.agent_group)"
yes, I strongly believe we removing code that are not being used would be good to don't confuse other programmers that can be working on the code futurely.

2023-04-28 17:12 UTC, gpazuch approved these changes
LGTM :+1:

2023-04-28 20:49 UTC, etaques approved these changes
LGTM

2023-04-29 19:10 UTC, merged